name: saycan
channels:
  - pytorch
  - nvidia/label/cuda-11.6.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.11.17=hbcca054_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py38h5eee18b_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=41.0.3=py38hdda0065_0
  - cuda=11.6.0=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.0=0
  - cuda-compiler=11.6.0=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.55=h9dd2d0c_0
  - cuda-cupti=11.6.55=h43c5c43_0
  - cuda-cuxxfilt=11.6.55=h69de05d_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.6.55=hff0b7d4_0
  - cuda-libraries=11.6.0=0
  - cuda-libraries-dev=11.6.0=0
  - cuda-memcheck=11.6.55=h0288dce_0
  - cuda-nsight=11.6.55=0
  - cuda-nsight-compute=11.6.0=0
  - cuda-nvcc=11.6.55=h5758ece_0
  - cuda-nvdisasm=11.6.55=h5556c0d_0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.6.55=h30b2dac_0
  - cuda-nvprune=11.6.55=h3791f62_0
  - cuda-nvrtc=11.6.55=hc54fff9_0
  - cuda-nvrtc-dev=11.6.55=h42ad0f4_0
  - cuda-nvtx=11.6.55=h99d0529_0
  - cuda-nvvp=11.6.58=h67ee751_0
  - cuda-runtime=11.6.0=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.6.55=h4716e2e_0
  - cuda-toolkit=11.6.0=0
  - cuda-tools=11.6.0=0
  - cuda-visual-tools=11.6.0=0
  - debugpy=1.6.7=py38h6a678d5_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.2.0.100=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.12.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.11.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py38h578d9bd_0
  - jupyter_server=1.24.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.8.1.74=h1e58c10_0
  - libcublas-dev=11.8.1.74=h7a51e1f_0
  - libcufft=10.7.0.55=h563f203_0
  - libcufft-dev=10.7.0.55=h05eb8d0_0
  - libcufile=1.2.0.100=0
  - libcufile-dev=1.2.0.100=0
  - libcurand=10.2.9.55=h7c349da_0
  - libcurand-dev=10.2.9.55=hd2e71f0_0
  - libcusolver=11.3.2.55=hebb49eb_0
  - libcusparse=11.7.1.55=h9a152cf_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.6.0.55=hdb0c674_0
  - libnpp-dev=11.6.0.55=h0163868_0
  - libnvjpeg=11.6.0.55=h6f17e28_0
  - libnvjpeg-dev=11.6.0.55=h0163868_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - nbclassic=1.0.0=pyh8b2e9e2_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.11.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.6=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nsight-compute=2022.1.0.12=0
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.2.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.31.0=pyhd8ed1ab_0
  - requests=2.31.0=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.0=pyh0d859eb_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py38_cu116
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - annotated-types==0.6.0
      - astunparse==1.6.3
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - chex==0.1.7
      - clip==1.0
      - colorama==0.4.6
      - commonmark==0.9.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - distro==1.8.0
      - dm-tree==0.1.8
      - easydict==1.11
      - filelock==3.13.1
      - flax==0.5.3
      - fonttools==4.45.0
      - fsspec==2023.10.0
      - ftfy==6.1.3
      - fvcore==0.1.5.post20221221
      - gdown==4.7.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.1
      - imageio==2.33.0
      - imageio-ffmpeg==0.4.5
      - importlib-metadata==6.8.0
      - iopath==0.1.10
      - jax==0.4.13
      - jaxlib==0.4.13
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - ml-dtypes==0.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.3.4
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - optax==0.1.7
      - pillow==10.1.0
      - portalocker==2.8.2
      - proglog==0.1.10
      - pybullet==3.2.5
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pyparsing==3.1.1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - rich==11.2.0
      - scipy==1.10.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorstore==0.1.45
      - termcolor==2.3.0
      - toolz==0.12.0
      - torch==2.1.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - triton==2.1.0
      - urllib3==2.1.0
      - yacs==0.1.8
prefix: /home/airlab/miniconda3/envs/saycan
